### ISSUE TITLE
Add/use new `current-state-version` endpoint

### ISSUE THREAD

**Issue by nickatsegment** [segmentio/terraform-enterprise-go#11]
https://www.terraform.io/docs/enterprise/api/state-versions.html#fetch-the-current-state-version-for-a-workspace
- No pagination nonsense
- Presumably more efficient on their end (less timeouts!)

**Comment by nickatsegment** [comment]
Updated my branch https://github.com/segmentio/terraform-enterprise-go/compare/use-get-current-state-version

Now there's a method DownloadLatestStateVersion that'll do just that as (request) efficiently as possible.

I did some benchmarks:
```
# old API
go test -v . -bench=DownloadStateVersionLatest -benchtime 10s -count 10 -run '^$' -args -enable-live -token $ATLAS_TOKEN -org segment -workspace tooling-stage
goos: darwin
goarch: amd64
pkg: github.com/segmentio/terraform-enterprise-go
BenchmarkDownloadStateVersionLatest-4   	      10	1896794636 ns/op
BenchmarkDownloadStateVersionLatest-4   	      10	1693860012 ns/op
BenchmarkDownloadStateVersionLatest-4   	      10	2449609560 ns/op
BenchmarkDownloadStateVersionLatest-4   	      10	2146172542 ns/op
BenchmarkDownloadStateVersionLatest-4   	      10	2394463618 ns/op
BenchmarkDownloadStateVersionLatest-4   	       5	2257663777 ns/op
BenchmarkDownloadStateVersionLatest-4   	      10	2160906782 ns/op
BenchmarkDownloadStateVersionLatest-4   	      10	2357306538 ns/op
BenchmarkDownloadStateVersionLatest-4   	      10	2295472588 ns/op
BenchmarkDownloadStateVersionLatest-4   	      10	1907426055 ns/op
PASS
ok  	github.com/segmentio/terraform-enterprise-go	246.540s
```

```
# new API
go test -v . -bench=DownloadStateVersionLatest -benchtime 10s -count 10 -run '^$' -args -enable-live -token $ATLAS_TOKEN -org segment -workspace tooling-stage
goos: darwin
goarch: amd64
pkg: github.com/segmentio/terraform-enterprise-go
BenchmarkDownloadStateVersionLatest-4   	      10	1735183260 ns/op
BenchmarkDownloadStateVersionLatest-4   	      10	1064043689 ns/op
BenchmarkDownloadStateVersionLatest-4   	       5	2298189465 ns/op
BenchmarkDownloadStateVersionLatest-4   	      10	1228552243 ns/op
BenchmarkDownloadStateVersionLatest-4   	      10	1226431714 ns/op
BenchmarkDownloadStateVersionLatest-4   	      10	1471945658 ns/op
BenchmarkDownloadStateVersionLatest-4   	      10	1675950562 ns/op
BenchmarkDownloadStateVersionLatest-4   	      10	1293584491 ns/op
BenchmarkDownloadStateVersionLatest-4   	      10	1363993219 ns/op
BenchmarkDownloadStateVersionLatest-4   	      10	1122328696 ns/op
PASS
ok  	github.com/segmentio/terraform-enterprise-go	168.654s
```

(Pretty sure Golang benchmarks weren't designed for network, considering the fairly high variability.)

There are probably hidden factors here. But seems like the new code is about 1s better than the old, despite having to do more requests.

**Comment by nickatsegment** [comment]
@dfuentes @systemizer @boggsboggs What do you think about these findings? They're sort of unintuitive to me.

**Comment by dfuentes** [comment]
It makes sense to me that it could be faster.  By not needing pagination or collection responses, they can probably query the DB more efficiently (by using a single WHERE based on workspace id instead of multiple WHERE's based on filters) and avoid unnecessary serialization overhead as well.

I'm really glad that they are actually documenting and expanding these API's.  For some history on why the implementation is a little wonky right now, when I wrote this lib, none of the `state-version` API's were documented and I was just going off of the requests I could sniff in the chrome dev tools while navigating around the UI.

**Comment by systemizer** [comment]
Using the latest endpoint makes sense to me. also thanks for adding docstrings!
